%YAML:1.0

rgb_path_1st : "./data/0000000071.png" 
rgb_path_2st : "./data/0000000075.png" 
tif_path_1st : "./data/0000000071_pred.tif"
tif_path_2st : "./data/0000000075_pred.tif"
cam2can_calib_path : "./data/calib_cam_to_cam.txt"  
poses_path : "./data/poses.txt" 
